<a href="https://colab.research.google.com/github/h-kayotin/hanayo_homework/blob/master/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/02_%E5%88%9D%E5%A7%8B%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 加载数据集
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
# 查看训练数据
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
# 查看测试数据
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)


10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
# 神经网络架构
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [ ]:
# 编译
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [ ]:
# 准备图像数据
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [ ]:
# 拟合模型
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 3s 6ms/step - loss: 0.2660 - accuracy: 0.9235
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 0.1064 - accuracy: 0.9685
Epoch 3/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0700 - accuracy: 0.9792
Epoch 4/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0505 - accuracy: 0.9849
Epoch 5/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0382 - accuracy: 0.9886


In [ ]:
# 利用模型进行预测
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 58ms/step


array([3.2556463e-07, 3.8430787e-09, 2.7273702e-06, 3.8403316e-05,
       1.1657525e-12, 4.5575778e-08, 3.7694023e-12, 9.9995726e-01,
       3.3784396e-08, 1.1033820e-06], dtype=float32)

In [ ]:
predictions[0].argmax()

7

In [ ]:
predictions[0][7]

0.99995726

In [ ]:
# 可以看到7的概率最大，是99%，也确实是7
test_labels[0]

7

In [ ]:
# 在新数据上评估模型
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 0s 1ms/step - loss: 0.0620 - accuracy: 0.9809
test_acc: 0.98089998960495


In [19]:
import numpy as np
x = np.array(12)
x

array(12)

In [20]:
x.ndim

0

In [21]:
x = np.array([12, 3, 6, 14, 7])
x

array([12,  3,  6, 14,  7])

In [22]:
x.ndim

1

In [23]:
# 矩阵是2阶张量
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [24]:
# 3阶张量，由多个矩阵组成
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

3

In [25]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [26]:
# 轴的个数，说明训练数据是一个3阶张量
train_images.ndim

3

In [27]:
# 训练数据的形状
train_images.shape

(60000, 28, 28)